resources:
- name: concourse-git
  type: git
  icon: github
  source:
    uri: https://github.com/niteesh6024/concourse.git

jobs:
- name: job
  plan:
  - get: concourse-git
    trigger: true
  - task: task-1
    config:
      inputs:
        - name: concourse-git
      outputs:
        - name: output-concourse-git
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: nginx }
      run:
        path: sh
        args: 
          - -c #tells to read multiple inputs
          - |
            ls
            pwd
            echo  > ./../output-concourse-git/app.txt
        dir: concourse-git
  - task: task-2
    config:
      inputs:
        - name: output-concourse-git
      platform: linux
      image_resource:
        type: docker-image
        source: { repository: nginx }
      run:
        path: sh
        args: 
          - -c #tells to read multiple inputs
          - |
            ls
            pwd
            
        dir: output-concourse-git