---
resources:
- name: concourse-git
  type: git
  icon: github
  check_every: 1m
  source:
    uri: https://github.com/niteesh6024/concourse.git


jobs:
# update this pipeline before updating child pipelines
- name: set-self
  public: true
  plan:
  - get: concourse-git
    trigger: true
  - set_pipeline: self
    file: concourse-git/set-pipeline.yml

- name: set-example-pipelines
  public: true
  plan:
  - get: concourse-git
    trigger: true
    passed: [set-self]
  - set_pipeline: hello-world-job
    file: concourse-git/hello-world.yml
  - set_pipeline: separate-task-config
    file: concourse-git/task-config-separate.yaml
  - set_pipeline: pipeline-vars
    file: concourse-git/vars-fly.yaml
    vars:
      first: initial
      number: 4384
      hello: niteesh satya sai
  - set_pipeline: pipeline-vars-file
    file: concourse-git/vars-fly.yaml
    var_files:
      - concourse-git/vars-file.yml
  - set_pipeline: task-passing-artifact
    file: concourse-git/file-sharing-task.yaml
  - set_pipeline: time-triggered
    file: concourse-git/time-trigger.yaml
  - set_pipeline: git-triggered
    file: concourse-git/git-trigger.yaml
  - set_pipeline: manual-trigger
    file: concourse-git/chaining.yaml
  - set_pipeline: hooks
    file: concourse-git/task-hook.yaml

