---
task-config: &task-config
  platform: linux
  image_resource:
    type: docker-image
    source: { repository: alpine }
  inputs:
  - name: concourse-git

resources:
- name: concourse-git
  type: git
  icon: github
  source:
    uri: https://github.com/niteesh6024/concourse.git

jobs:
- name: slack-notification-job
  plan:
    - get: concourse-git
      trigger: trues

    - task: failing-task
      config:
        << : *task-config
        run:
          path: sh
          args:
            - -exc
            - exit 1


  on_failure:
    task: job-failure
    config:
      << : *task-config
      run:
        path: sh
        args:
          - -exc
          - |
            ./slack.sh
            echo $URL
            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$URL"'"}' https://hooks.slack.com/services/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
        dir: concourse-git
      params:
        BUILD_PIPELINE_NAME: ${BUILD_PIPELINE_NAME}
        BUILD_JOB_NAME: ${BUILD_JOB_NAME}
        BUILD_NAME: ${BUILD_NAME} 
        BUILD_PIPELINE_INSTANCE_VARS: ${BUILD_PIPELINE_INSTANCE_VARS}
        ATC_EXTERNAL_URL: ${ATC_EXTERNAL_URL}