---
task-config: &task-config
  platform: linux
  image_resource:
    type: docker-image
    source: { repository: alpine/git }
  inputs:
  - name: concourse-git

resources:
- name: concourse-git
  type: git
  icon: github
  source:
    uri: https://github.com/niteesh6024/concourse.git
- name: notify
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

jobs:
- name: slack-notification-job
  plan:
    - get: concourse-git
      trigger: true

    - task: failing-task
      config:
        << : *task-config
        run:
          path: sh
          args:
            - -exc
            - exit 1; cd concourse-git/.git; ls -la; cat committer_name; cat commit_message;
          

  on_failure:
    put: notify
    params:
      text: |
        "${BUILD_PIPELINE_NAME} » ${BUILD_JOB_NAME} » ${BUILD_NAME} - ${BUILD_PIPELINE_INSTANCE_VARS} triggered by "
        ((instance_var))
        "$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
      silent: true 