resources:
- name: concourse-git
  type: git
  icon: github
  source:
    uri: https://github.com/niteesh6024/concourse.git

jobs:
- name: job
  public: true
  plan:
  - get: concourse-git
  - task: simple-task
    file: concourse-git/extra/hello-world.yaml