---
task-config: &task-config
  platform: linux
  image_resource:
    type: registry-image
    source: { repository: nginx }
  inputs:
  - name: concourse-git

resources:
- name: concourse-git
  type: git
  icon: github
  source:
    uri: https://github.com/niteesh6024/concourse.git

jobs:
- name: job
  plan:
    - get: concourse-git
      trigger: true
    - task: successful-task
      config:
        << : *task-config
        run:
          path: echo
          args: ["echo","success!!!"]
      on_success:
        task: task-success
        config:
          << : *task-config
          run:
            path: echo
            args: ["This task succeeded!"]
      on_abort:
        task: task-aborted
        config:
          << : *task-config
          run:
            path: echo
            args: ["This task was aborted!"]
    - task: failing-task
      config:
        << : *task-config
        run:
          path: sh
          args: ["-lc", "exit 1"]
      on_failure:
        task: task-failure
        config:
          << : *task-config
          run:
            path: echo
            args: ["This task failed!"]
  on_success:
    task: job-success
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job succeeded!"]
  on_failure:
    task: job-failure
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job failed!"]
  on_abort:
    task: job-aborted
    config:
      << : *task-config
      run:
        path: echo
        args: ["This job was aborted!"]