resources:
- name: concourse-git
  type: git
  icon: github
  source:
    uri: https://github.com/niteesh6024/concourse.git

jobs:
- name: job-gcp-test
  plan:
  - get: concourse-git
    trigger: true
  - task: task-1
    config:
      inputs:
        - name: concourse-git
      outputs:
        - name: concourse-git
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: google/cloud-sdk
          tag: alpine
      run:
        path: /bin/bash
        args:
          - -ceux #tells to read multiple inputs
          - |
            echo $SA_KEY_JSON > ./sa-key.json
            gcloud auth activate-service-account --key-file=./sa-key.json
            gcloud container images list-tags europe-west2-docker.pkg.dev/uk-sa-observability-preprod/artifact/hpe-oneview --format="get(tags)"  > ./EXISTING_VERSION1.txt
            gcloud container images list-tags europe-west2-docker.pkg.dev/uk-sa-observability-prod/artifact/hpe-oneview --format="get(tags)" > ./EXISTING_VERSION2.txt  
            cat EXISTING_VERSION1.txt
            cat EXISTING_VERSION2.txt
        dir: concourse-git
      params:
        SA_KEY_JSON: ((uk-sa-observability-prod-sa-key))
        

  - task: task-2
    config:
      inputs:
        - name: concourse-git
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: google/cloud-sdk
          tag: alpine
      run:
        path: /bin/bash
        args:
          - -ceux #tells to read multiple inputs
          - |
            
            cat EXISTING_VERSION1.txt
            cat EXISTING_VERSION2.txt
        dir: concourse-git
